import { useMemo, useState } from "react";
import {
  AlertTriangle, Bell, Building2, CalendarClock, CheckCircle2, ChevronRight, ClipboardCheck,
  Download, FileText, FolderOpen, LayoutDashboard, MapPinned, Menu, Pencil, Plus, RotateCcw,
  Search, Settings, ShieldCheck, TowerControl, Upload, UserCog, Users, X,
} from "lucide-react";
import { AppProvider, useApp } from "./context/AppContext";
import { REGION_LABELS } from "./data/masterData";
import {
  addReviewMonths, formatDate, getAreaProgress, getAreaStatus, getBangkokInputDate, getComplianceStatus,
  validateComplianceDates, validateFile,
} from "./lib/dashboard";
import ThailandMap from "./components/ThailandMap";
import { Badge, Button, Card, Dialog, Progress, cn } from "./components/ui";

const STATUS_META = {
  pending: { label: "รอดำเนินการ", tone: "pending" },
  complete: { label: "ครบถ้วน", tone: "complete" },
  "due-soon": { label: "ใกล้ครบกำหนด", tone: "due-soon" },
  overdue: { label: "เกินกำหนด", tone: "overdue" },
};
const ROLE_LABELS = { admin: "ผู้ดูแลระบบ", editor: "ผู้รับผิดชอบพื้นที่", viewer: "ผู้ตรวจสอบ" };
const topicIcons = [ShieldCheck, ClipboardCheck, AlertTriangle, Users, UserCog, FileText, CheckCircle2];

export default function App() { return <AppProvider><DashboardApp /></AppProvider>; }

function DashboardApp() {
  const { state, dispatch, kpis, reminders } = useApp();
  const [complianceTarget, setComplianceTarget] = useState(null);
  const [documentTarget, setDocumentTarget] = useState(null);
  const [toast, setToast] = useState("");
  const isAdmin = state.currentUser.role === "admin";
  const canEdit = state.currentUser.role !== "viewer";
  const activeTopics = state.topics.filter((topic) => topic.active);
  const notify = (message) => { setToast(message); window.setTimeout(() => setToast(""), 3000); };
  const navigation = [
    { id: "overview", label: state.settings.overviewLabel, icon: LayoutDashboard },
    { id: "areas", label: "พื้นที่รับผิดชอบ", icon: MapPinned, count: 32 },
    ...activeTopics.map((topic, index) => ({ id: `topic:${topic.id}`, label: topic.shortName, icon: topicIcons[index % topicIcons.length] })),
    { id: "documents", label: "ทะเบียนเอกสาร", icon: FolderOpen },
    { id: "reminders", label: "การแจ้งเตือนรอบทบทวน", icon: CalendarClock, count: reminders.length || null },
  ];
  const setPanel = (panel) => dispatch({ type: "SET_ACTIVE_PANEL", panel });
  return (
    <div className="app-shell">
      {state.ui.sidebarOpen && <button className="mobile-overlay" aria-label="ปิดเมนู" onClick={() => dispatch({ type: "TOGGLE_SIDEBAR" })} />}
      <aside className={cn("app-sidebar", state.ui.sidebarOpen && "is-open")}>
        <div className="brand-block"><span className="brand-mark"><ShieldCheck size={25} /></span><div><strong>AEROTHAI</strong><span>Security Standards</span></div><Button variant="ghost-inverse" size="icon" className="sidebar-close" onClick={() => dispatch({ type: "TOGGLE_SIDEBAR" })} aria-label="ปิดเมนู"><X size={20} /></Button></div>
        <div className="sidebar-label">ระบบติดตามมาตรฐาน</div>
        <nav className="sidebar-nav" aria-label="เมนูหลัก">{navigation.map(({ id, label, icon: Icon, count }) => <button key={id} className={cn("nav-item", state.activePanel === id && "is-active")} onClick={() => setPanel(id)}><Icon size={18} /><span>{label}</span>{count ? <em>{count}</em> : null}</button>)}</nav>
        <div className="sidebar-footer"><div className="profile-avatar">{state.settings.adminPhoto ? <img src={state.settings.adminPhoto} alt="รูปผู้ดูแล" /> : <UserCog size={20} />}</div><div><strong>{state.settings.adminDisplayName}</strong><span>{ROLE_LABELS[state.currentUser.role]}</span></div>{isAdmin && <Button variant="ghost-inverse" size="icon" onClick={() => dispatch({ type: "OPEN_ADMIN" })} aria-label="ตั้งค่าผู้ดูแล"><Settings size={18} /></Button>}</div>
      </aside>
      <main className="main-shell">
        <header className="top-header"><div className="header-title-wrap"><Button variant="secondary" size="icon" className="mobile-menu" onClick={() => dispatch({ type: "TOGGLE_SIDEBAR" })} aria-label="เปิดเมนู"><Menu size={20} /></Button><div><h1>{state.settings.dashboardName}</h1><p>{state.settings.organizationName}</p></div></div><div className="header-actions"><label className="role-switcher"><span>บทบาทจำลอง</span><select value={state.currentUser.role} onChange={(event) => dispatch({ type: "SET_CURRENT_USER_ROLE", role: event.target.value })}><option value="admin">Admin</option><option value="editor">Area Editor</option><option value="viewer">Viewer</option></select></label><Button variant="secondary" size="icon" className="notification-button" onClick={() => setPanel("reminders")} aria-label={`การแจ้งเตือน ${reminders.length} รายการ`}><Bell size={19} />{reminders.length > 0 && <span>{reminders.length}</span>}</Button>{canEdit && <Button onClick={() => setComplianceTarget({ areaId: state.selectedAreaId, topicId: activeTopics[0]?.id })}><Plus size={17} /> เพิ่มข้อมูล</Button>}{isAdmin && <Button variant="secondary" size="icon" onClick={() => dispatch({ type: "OPEN_ADMIN" })} aria-label="ตั้งค่า Dashboard"><Settings size={19} /></Button>}</div></header>
        <div className="content-shell">
          {state.activePanel === "overview" && <Overview kpis={kpis} reminders={reminders} onEdit={setComplianceTarget} onDocuments={setDocumentTarget} onViewReminders={() => setPanel("reminders")} />}
          {state.activePanel === "areas" && <AreasPanel onEdit={setComplianceTarget} onDocuments={setDocumentTarget} />}
          {state.activePanel.startsWith("topic:") && <TopicPanel topicId={state.activePanel.split(":")[1]} onEdit={setComplianceTarget} onDocuments={setDocumentTarget} />}
          {state.activePanel === "documents" && <DocumentsPanel onOpen={setDocumentTarget} />}
          {state.activePanel === "reminders" && <ReminderPanel reminders={reminders} onEdit={setComplianceTarget} />}
        </div>
      </main>
      <ComplianceDialog target={complianceTarget} onClose={() => setComplianceTarget(null)} onSaved={() => { setComplianceTarget(null); notify("บันทึกข้อมูลมาตรฐานแล้ว"); }} />
      <DocumentDialog target={documentTarget} onClose={() => setDocumentTarget(null)} notify={notify} />
      <AdminDialog open={state.ui.adminDialogOpen} onClose={() => dispatch({ type: "CLOSE_ADMIN" })} notify={notify} />
      <div className={cn("toast", toast && "is-visible")} role="status" aria-live="polite"><CheckCircle2 size={18} />{toast}</div>
    </div>
  );
}

function Overview({ kpis, reminders, onEdit, onDocuments, onViewReminders }) {
  const cards = [
    ["ศูนย์ควบคุมหลัก", kpis.centers, "ครอบคลุมทุกภูมิภาค", Building2, "blue"],
    ["หอลูกข่าย", kpis.towers, "พื้นที่ปฏิบัติการ", TowerControl, "cyan"],
    ["รอดำเนินการ", kpis.pending, "รายการที่ยังไม่มีข้อมูล", ClipboardCheck, "amber"],
    ["ใกล้ครบกำหนด", kpis.dueSoon, "ภายใน 90 วัน", CalendarClock, "orange"],
    ["เกินกำหนด", kpis.overdue, "ต้องติดตามทันที", AlertTriangle, "red"],
    ["ความครบถ้วน", `${kpis.completion}%`, "จากรายการที่เปิดใช้งาน", ShieldCheck, "green"],
  ];
  return <><section className="page-heading"><div><p className="eyebrow">ภาพรวมระบบ</p><h2>สถานะความมั่นคงทั่วประเทศ</h2><p>ติดตามความพร้อมของศูนย์หลัก หอลูกข่าย และรอบทบทวนในหน้าจอเดียว</p></div><span className="live-chip"><i /> ข้อมูลจำลองบนอุปกรณ์นี้</span></section><section className="kpi-grid">{cards.map(([label, value, helper, Icon, tone]) => <Card key={label} className="kpi-card"><div className={`kpi-icon kpi-icon--${tone}`}><Icon size={20} /></div><p>{label}</p><strong>{value}</strong><span>{helper}</span></Card>)}</section><section className="dashboard-grid"><Card className="map-card"><SectionHeader eyebrow="เครือข่ายพื้นที่" title="แผนที่ศูนย์ควบคุมการบิน" description="เลือกศูนย์หลักเพื่อแสดงหอลูกข่ายในความรับผิดชอบ" /><ThailandMap /></Card><AreaList /></section><ComplianceDetail onEdit={onEdit} onDocuments={onDocuments} /><Card className="reminder-preview"><SectionHeader eyebrow="Reminder center" title="รายการที่ต้องติดตาม" description={reminders.length ? `${reminders.length} รายการภายใน 90 วันหรือเกินกำหนด` : "ยังไม่มีรายการใกล้ครบกำหนด"} action={<Button variant="secondary" onClick={onViewReminders}>ดูทั้งหมด <ChevronRight size={16} /></Button>} />{reminders.length ? <ReminderRows reminders={reminders.slice(0, 5)} /> : <EmptyState icon={CalendarClock} title="ยังไม่มีรายการแจ้งเตือน" description="เมื่อบันทึกวันที่ดำเนินการ ระบบจะคำนวณรอบทบทวนและแสดงรายการที่นี่" />}</Card></>;
}

function AreasPanel({ onEdit, onDocuments }) { return <><section className="page-heading"><div><p className="eyebrow">พื้นที่รับผิดชอบ</p><h2>ศูนย์หลักและหอลูกข่าย 32 พื้นที่</h2><p>ค้นหา เลือก และตรวจสอบความครบถ้วนของแต่ละพื้นที่</p></div></section><section className="dashboard-grid"><Card className="map-card"><ThailandMap /></Card><AreaList /></section><ComplianceDetail onEdit={onEdit} onDocuments={onDocuments} /></>; }
function SectionHeader({ eyebrow, title, description, action }) { return <header className="section-header"><div>{eyebrow && <p className="eyebrow">{eyebrow}</p>}<h3>{title}</h3>{description && <p>{description}</p>}</div>{action}</header>; }

function AreaList() {
  const { state, dispatch } = useApp();
  const centers = useMemo(() => { const search = state.filters.search.trim().toLowerCase(); return state.areas.filter((area) => area.type === "center").filter((center) => { const children = state.areas.filter((area) => area.parentCenterId === center.id); return (!search || center.name.toLowerCase().includes(search) || children.some((tower) => tower.name.toLowerCase().includes(search))) && (state.filters.region === "all" || center.regionKey === state.filters.region) && (state.filters.status === "all" || getAreaStatus(state, center.id) === state.filters.status); }); }, [state]);
  return <Card className="area-list-card"><SectionHeader eyebrow="Area status" title="สถานะรายศูนย์" description={`พบ ${centers.length} ศูนย์จากทั้งหมด 9 แห่ง`} /><div className="filter-stack"><label className="search-field"><Search size={17} /><input value={state.filters.search} onChange={(event) => dispatch({ type: "UPDATE_FILTERS", filters: { search: event.target.value } })} placeholder="ค้นหาศูนย์หรือหอลูกข่าย" aria-label="ค้นหาพื้นที่" /></label><div className="filter-row"><label><span>ภูมิภาค</span><select value={state.filters.region} onChange={(event) => dispatch({ type: "UPDATE_FILTERS", filters: { region: event.target.value } })}><option value="all">ทุกภูมิภาค</option>{Object.entries(REGION_LABELS).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label><label><span>สถานะ</span><select value={state.filters.status} onChange={(event) => dispatch({ type: "UPDATE_FILTERS", filters: { status: event.target.value } })}><option value="all">ทุกสถานะ</option>{Object.entries(STATUS_META).map(([key, meta]) => <option key={key} value={key}>{meta.label}</option>)}</select></label></div></div><div className="area-scroll">{centers.map((center) => { const active = center.id === state.selectedCenterId; const towers = state.areas.filter((area) => area.parentCenterId === center.id); const progress = getAreaProgress(state, center.id); return <article key={center.id} className={cn("area-item", active && "is-active")}><button className="area-item-main" onClick={() => dispatch({ type: "SELECT_AREA", areaId: center.id })}><span className="area-icon"><Building2 size={17} /></span><span className="area-copy"><strong>{center.shortName}</strong><small>{REGION_LABELS[center.regionKey]} · {towers.length} หอลูกข่าย</small></span><StatusBadge status={getAreaStatus(state, center.id)} /></button><div className="area-progress-row"><Progress value={progress} label={`ความครบถ้วนศูนย์${center.shortName}`} /><span>{progress}%</span></div>{active && <div className="tower-list">{towers.map((tower) => <button key={tower.id} className={cn(tower.id === state.selectedAreaId && "is-selected")} onClick={() => dispatch({ type: "SELECT_AREA", areaId: tower.id })}><TowerControl size={14} />{tower.shortName}<ChevronRight size={14} /></button>)}</div>}</article>; })}{!centers.length && <EmptyState icon={Search} title="ไม่พบพื้นที่" description="ลองเปลี่ยนคำค้นหาหรือตัวกรอง" compact />}</div></Card>;
}

function ComplianceDetail({ onEdit, onDocuments }) {
  const { state } = useApp(); const area = state.areas.find((item) => item.id === state.selectedAreaId); const topics = state.topics.filter((topic) => topic.active);
  return <Card className="compliance-section"><SectionHeader eyebrow="Compliance detail" title={area?.name || "รายละเอียดพื้นที่"} description={`${REGION_LABELS[area?.regionKey]} · ${area?.type === "center" ? "ศูนย์ควบคุมหลัก" : "หอลูกข่าย"}`} action={<StatusBadge status={getAreaStatus(state, area?.id)} />} /><div className="compliance-grid">{topics.map((topic, index) => { const record = state.complianceRecords.find((item) => item.areaId === area.id && item.topicId === topic.id); const status = getComplianceStatus(record); const Icon = topicIcons[index % topicIcons.length]; return <article key={topic.id} className="compliance-card"><div className="compliance-card-top"><span className="topic-icon"><Icon size={19} /></span><StatusBadge status={status} /></div><h4>{topic.shortName}</h4><p>{topic.name}</p><dl><div><dt>ดำเนินการล่าสุด</dt><dd>{formatDate(record?.lastReviewDate)}</dd></div><div><dt>ครบกำหนด</dt><dd>{formatDate(record?.nextReviewDate)}</dd></div></dl><div className="compliance-actions">{state.currentUser.role !== "viewer" && <Button variant="secondary" onClick={() => onEdit({ areaId: area.id, topicId: topic.id })}><Pencil size={15} /> บันทึกข้อมูล</Button>}<Button variant="ghost" onClick={() => onDocuments({ areaId: area.id, topicId: topic.id })}><FolderOpen size={15} /> เอกสาร {record?.documents.length ? `(${record.documents.length})` : ""}</Button></div></article>; })}</div></Card>;
}

function TopicPanel({ topicId, onEdit, onDocuments }) {
  const { state, dispatch } = useApp(); const topic = state.topics.find((item) => item.id === topicId); const rows = state.areas.map((area) => ({ area, record: state.complianceRecords.find((record) => record.areaId === area.id && record.topicId === topicId) }));
  return <><section className="page-heading"><div><p className="eyebrow">{state.settings.dataManagementLabel}</p><h2>{topic?.name}</h2><p>รอบทบทวนทุก {topic?.reviewIntervalMonths} เดือน · ตรวจสอบครบทั้ง 32 พื้นที่</p></div></section><Card className="data-table-card"><div className="responsive-table"><table><thead><tr><th>พื้นที่</th><th>ประเภท</th><th>สถานะ</th><th>ดำเนินการล่าสุด</th><th>ครบกำหนด</th><th><span className="sr-only">การทำงาน</span></th></tr></thead><tbody>{rows.map(({ area, record }) => <tr key={area.id}><td><button className="table-area-link" onClick={() => dispatch({ type: "SELECT_AREA", areaId: area.id })}>{area.shortName}</button><small>{REGION_LABELS[area.regionKey]}</small></td><td>{area.type === "center" ? "ศูนย์หลัก" : "หอลูกข่าย"}</td><td><StatusBadge status={getComplianceStatus(record)} /></td><td>{formatDate(record?.lastReviewDate)}</td><td>{formatDate(record?.nextReviewDate)}</td><td><div className="row-actions">{state.currentUser.role !== "viewer" && <Button size="icon" variant="ghost" onClick={() => onEdit({ areaId: area.id, topicId })} aria-label={`แก้ไข ${area.shortName}`}><Pencil size={16} /></Button>}<Button size="icon" variant="ghost" onClick={() => onDocuments({ areaId: area.id, topicId })} aria-label={`เอกสาร ${area.shortName}`}><FolderOpen size={16} /></Button></div></td></tr>)}</tbody></table></div></Card></>;
}

function DocumentsPanel({ onOpen }) {
  const { state } = useApp(); const documents = state.complianceRecords.flatMap((record) => record.documents.map((document) => ({ ...document, record })));
  return <><section className="page-heading"><div><p className="eyebrow">Document register</p><h2>ทะเบียนเอกสารจำลอง</h2><p>ไฟล์จะดาวน์โหลดได้เฉพาะใน session ปัจจุบันและไม่ถูกส่งไปยัง server</p></div></section><Card>{documents.length ? <div className="document-grid">{documents.map((document) => { const area = state.areas.find((item) => item.id === document.areaId); const topic = state.topics.find((item) => item.id === document.topicId); return <article key={document.id} className="document-card"><span><FileText size={22} /></span><div><strong>{document.name}</strong><p>{area?.shortName} · {topic?.shortName}</p><small>{formatBytes(document.size)} · {formatDate(document.selectedAt)}</small></div><a className="ui-button ui-button--secondary ui-button--icon" href={document.objectUrl} download={document.name} aria-label={`ดาวน์โหลด ${document.name}`}><Download size={17} /></a></article>; })}</div> : <EmptyState icon={FolderOpen} title="ยังไม่มีเอกสารใน session นี้" description="เปิดหัวข้อมาตรฐานของพื้นที่และเลือก “เอกสาร” เพื่อเพิ่มไฟล์จำลอง" action={<Button onClick={() => onOpen({ areaId: state.selectedAreaId, topicId: state.topics.find((topic) => topic.active)?.id })}><Upload size={17} /> เพิ่มเอกสาร</Button>} />}</Card></>;
}

function ReminderPanel({ reminders, onEdit }) { return <><section className="page-heading"><div><p className="eyebrow">Reminder center</p><h2>การแจ้งเตือนรอบทบทวน</h2><p>จัดลำดับตามวันที่ครบกำหนดเพื่อช่วยวางแผนติดตาม</p></div><div className="severity-summary"><span className="danger">{reminders.filter((item) => item.bucket === "overdue").length} เกินกำหนด</span><span>{reminders.filter((item) => item.bucket !== "overdue").length} ภายใน 90 วัน</span></div></section><Card>{reminders.length ? <ReminderRows reminders={reminders} onEdit={onEdit} detailed /> : <EmptyState icon={CalendarClock} title="ยังไม่มีรายการแจ้งเตือน" description="บันทึกวันที่ดำเนินการในหัวข้อมาตรฐาน แล้วระบบจะจัดกลุ่มการแจ้งเตือนให้อัตโนมัติ" />}</Card></>; }
function ReminderRows({ reminders, onEdit, detailed = false }) { const { state } = useApp(); return <div className="reminder-list">{reminders.map((record) => { const area = state.areas.find((item) => item.id === record.areaId); const topic = state.topics.find((item) => item.id === record.topicId); const overdue = record.daysRemaining < 0; return <article key={record.id} className={cn("reminder-row", overdue && "is-overdue")}><span className="reminder-icon">{overdue ? <AlertTriangle size={18} /> : <CalendarClock size={18} />}</span><div className="reminder-copy"><strong>{topic?.shortName}</strong><p>{area?.name}</p>{detailed && <small>ครบกำหนด {formatDate(record.nextReviewDate)}</small>}</div><div className="reminder-days"><strong>{overdue ? `${Math.abs(record.daysRemaining)} วัน` : `${record.daysRemaining} วัน`}</strong><span>{overdue ? "เกินกำหนด" : "คงเหลือ"}</span></div>{onEdit && state.currentUser.role !== "viewer" && <Button variant="secondary" onClick={() => onEdit({ areaId: record.areaId, topicId: record.topicId })}>ดำเนินการ</Button>}</article>; })}</div>; }

function ComplianceDialog({ target, onClose, onSaved }) {
  const { state, dispatch } = useApp(); const record = target ? state.complianceRecords.find((item) => item.areaId === target.areaId && item.topicId === target.topicId) : null; const topic = target ? state.topics.find((item) => item.id === target.topicId) : null; const area = target ? state.areas.find((item) => item.id === target.areaId) : null; const [form, setForm] = useState({ lastReviewDate: "", note: "" }); const [error, setError] = useState(""); const initialKey = `${record?.id || "closed"}-${record?.updatedAt || "new"}`; const current = form._key === initialKey ? form : { _key: initialKey, lastReviewDate: record?.lastReviewDate || "", note: record?.note || "" }; const nextReviewDate = addReviewMonths(current.lastReviewDate, topic?.reviewIntervalMonths || 12); const update = (patch) => setForm({ ...current, ...patch });
  const save = (event) => { event.preventDefault(); const message = validateComplianceDates(current.lastReviewDate, nextReviewDate); if (message) { setError(message); return; } dispatch({ type: "UPDATE_COMPLIANCE_RECORD", record: { id: record.id, lastReviewDate: current.lastReviewDate, nextReviewDate, note: current.note.trim(), updatedAt: new Date().toISOString(), updatedBy: state.settings.adminDisplayName } }); setError(""); onSaved(); };
  return <Dialog open={Boolean(target)} onClose={onClose} title="บันทึกข้อมูลมาตรฐาน" description={area && topic ? `${area.name} · ${topic.shortName}` : ""}><form className="form-stack" onSubmit={save}><div className="form-grid"><label><span>วันที่ดำเนินการล่าสุด</span><input type="date" value={current.lastReviewDate} onChange={(event) => update({ lastReviewDate: event.target.value })} max={getBangkokInputDate()} required /></label><label><span>วันที่ครบกำหนดถัดไป</span><input type="date" value={nextReviewDate} readOnly aria-readonly="true" /></label></div><div className="calculation-note"><CalendarClock size={18} /><span>ระบบคำนวณรอบทบทวนอัตโนมัติทุก {topic?.reviewIntervalMonths} เดือน</span></div><label><span>หมายเหตุ</span><textarea rows="4" value={current.note} onChange={(event) => update({ note: event.target.value })} placeholder="บันทึกรายละเอียดเพิ่มเติม (ไม่บังคับ)" /></label>{error && <p className="form-error" role="alert"><AlertTriangle size={16} />{error}</p>}<div className="dialog-actions"><Button type="button" variant="secondary" onClick={onClose}>ยกเลิก</Button><Button type="submit"><CheckCircle2 size={17} /> บันทึกข้อมูล</Button></div></form></Dialog>;
}

function DocumentDialog({ target, onClose, notify }) {
  const { state, dispatch } = useApp(); const [error, setError] = useState(""); const record = target ? state.complianceRecords.find((item) => item.areaId === target.areaId && item.topicId === target.topicId) : null; const area = target ? state.areas.find((item) => item.id === target.areaId) : null; const topic = target ? state.topics.find((item) => item.id === target.topicId) : null;
  const addFile = (event) => { const file = event.target.files?.[0]; const message = validateFile(file); if (message) { setError(message); event.target.value = ""; return; } const document = { id: crypto.randomUUID(), name: file.name, type: file.type, size: file.size, areaId: target.areaId, topicId: target.topicId, selectedAt: new Date().toISOString(), objectUrl: URL.createObjectURL(file) }; dispatch({ type: "ADD_DOCUMENT_MOCK", recordId: record.id, document }); setError(""); notify(`เพิ่มไฟล์ ${file.name} แล้ว`); event.target.value = ""; };
  const remove = (document) => { if (!window.confirm(`นำไฟล์ “${document.name}” ออกจากรายการจำลองหรือไม่?`)) return; URL.revokeObjectURL(document.objectUrl); dispatch({ type: "REMOVE_DOCUMENT_MOCK", recordId: record.id, documentId: document.id }); };
  return <Dialog open={Boolean(target)} onClose={onClose} title="ทะเบียนเอกสาร" description={area && topic ? `${area.name} · ${topic.shortName}` : ""}><div className="document-dialog"><div className="sensitive-note"><ShieldCheck size={19} /><div><strong>สำหรับการสาธิตเท่านั้น</strong><p>ห้ามใช้ข้อมูลความมั่นคงหรือข้อมูลส่วนบุคคลจริง ไฟล์จะหายเมื่อปิด session</p></div></div>{state.currentUser.role !== "viewer" && <label className="file-drop"><Upload size={27} /><strong>เลือกเอกสารจากอุปกรณ์</strong><span>PDF, DOC, DOCX, XLS, XLSX · สูงสุด 10 MB</span><input type="file" accept=".pdf,.doc,.docx,.xls,.xlsx" onChange={addFile} /></label>}{error && <p className="form-error" role="alert"><AlertTriangle size={16} />{error}</p>}<div className="dialog-document-list">{record?.documents.length ? record.documents.map((document) => <article key={document.id}><span className="file-icon"><FileText size={20} /></span><div><strong>{document.name}</strong><small>{formatBytes(document.size)} · เลือกเมื่อ {new Intl.DateTimeFormat("th-TH", { dateStyle: "medium", timeStyle: "short" }).format(new Date(document.selectedAt))}</small></div><a href={document.objectUrl} download={document.name} className="ui-button ui-button--ghost ui-button--icon" aria-label={`ดาวน์โหลด ${document.name}`}><Download size={17} /></a>{state.currentUser.role !== "viewer" && <Button variant="ghost-danger" size="icon" onClick={() => remove(document)} aria-label={`นำ ${document.name} ออก`}><X size={17} /></Button>}</article>) : <EmptyState icon={FileText} title="ยังไม่มีเอกสาร" description="ไฟล์ที่เลือกจะแสดงในรายการนี้เฉพาะ session ปัจจุบัน" compact />}</div></div></Dialog>;
}

function AdminDialog({ open, onClose, notify }) {
  const { state, dispatch } = useApp(); const [form, setForm] = useState({ ...state.settings }); const [newTopic, setNewTopic] = useState(""); const [error, setError] = useState(""); const snapshotKey = `${state.settings.dashboardName}-${open}`; const current = form._key === snapshotKey ? form : { ...state.settings, _key: snapshotKey }; const update = (patch) => setForm({ ...current, ...patch });
  const imageChange = (event) => { const file = event.target.files?.[0]; if (!file) return; if (!/^image\/(jpeg|png|webp)$/.test(file.type) || file.size > 2 * 1024 * 1024) { setError("รูปต้องเป็น JPG, PNG หรือ WebP และมีขนาดไม่เกิน 2 MB"); return; } const reader = new FileReader(); reader.onload = () => update({ adminPhoto: reader.result }); reader.readAsDataURL(file); setError(""); };
  const save = (event) => { event.preventDefault(); if (!current.dashboardName.trim()) { setError("ชื่อ Dashboard ต้องไม่ว่าง"); return; } dispatch({ type: "UPDATE_SETTINGS", settings: { dashboardName: current.dashboardName.trim().slice(0, 100), organizationName: current.organizationName.trim(), adminDisplayName: current.adminDisplayName.trim(), adminPhoto: current.adminPhoto, overviewLabel: current.overviewLabel.trim(), dataManagementLabel: current.dataManagementLabel.trim(), internalSystemLabel: current.internalSystemLabel.trim() } }); notify("บันทึกการตั้งค่า Dashboard แล้ว"); onClose(); };
  const addTopic = () => { const name = newTopic.trim(); if (!name) return; dispatch({ type: "ADD_CUSTOM_TOPIC", topic: { id: `custom-${crypto.randomUUID()}`, name, shortName: name.slice(0, 40), reviewIntervalMonths: 12, active: true } }); setNewTopic(""); notify("เพิ่มหัวข้อใหม่ครบทั้ง 32 พื้นที่แล้ว"); };
  const toggle = (topic) => { if (topic.active && !window.confirm(`ปิดใช้งานหัวข้อ “${topic.shortName}” หรือไม่? ข้อมูลเดิมจะยังคงอยู่`)) return; dispatch({ type: "TOGGLE_CUSTOM_TOPIC", topicId: topic.id }); };
  const reset = () => { if (!window.confirm("รีเซ็ตข้อมูลจำลองและการตั้งค่าทั้งหมดกลับเป็นค่าเริ่มต้นหรือไม่?")) return; state.complianceRecords.forEach((record) => record.documents.forEach((document) => document.objectUrl && URL.revokeObjectURL(document.objectUrl))); dispatch({ type: "RESET_DEMO_DATA" }); notify("รีเซ็ตข้อมูลจำลองแล้ว"); onClose(); };
  return <Dialog open={open} onClose={onClose} title="ตั้งค่าผู้ดูแลระบบ" description="ปรับแต่งข้อมูลที่แสดงบนอุปกรณ์นี้" size="large"><form className="admin-form" onSubmit={save}><section><h3>ข้อมูล Dashboard</h3><div className="form-grid"><label className="full-width"><span>ชื่อ Dashboard</span><input value={current.dashboardName} maxLength={100} onChange={(event) => update({ dashboardName: event.target.value })} required /></label><label><span>ชื่อหน่วยงาน</span><input value={current.organizationName} onChange={(event) => update({ organizationName: event.target.value })} /></label><label><span>ชื่อผู้ดูแล</span><input value={current.adminDisplayName} onChange={(event) => update({ adminDisplayName: event.target.value })} /></label><label><span>ชื่อเมนูภาพรวม</span><input value={current.overviewLabel} onChange={(event) => update({ overviewLabel: event.target.value })} /></label><label><span>ชื่อกลุ่มเมนูข้อมูล</span><input value={current.dataManagementLabel} onChange={(event) => update({ dataManagementLabel: event.target.value })} /></label></div><div className="photo-picker"><div className="profile-avatar large">{current.adminPhoto ? <img src={current.adminPhoto} alt="ตัวอย่างรูปผู้ดูแล" /> : <UserCog size={26} />}</div><div><strong>รูปผู้ดูแลระบบ</strong><p>JPG, PNG หรือ WebP ขนาดไม่เกิน 2 MB</p></div><label className="ui-button ui-button--secondary">เลือกรูป<input type="file" accept="image/jpeg,image/png,image/webp" onChange={imageChange} /></label></div></section><section><h3>จัดการหัวข้อข้อมูล</h3><div className="add-topic-row"><input value={newTopic} onChange={(event) => setNewTopic(event.target.value)} placeholder="ชื่อหัวข้อใหม่ (รอบทบทวน 12 เดือน)" /><Button type="button" onClick={addTopic}><Plus size={16} /> เพิ่มหัวข้อ</Button></div><div className="topic-manager">{state.topics.map((topic) => <article key={topic.id}><div><strong>{topic.shortName}</strong><small>รอบทบทวน {topic.reviewIntervalMonths} เดือน</small></div><button type="button" className={cn("switch", topic.active && "is-on")} role="switch" aria-checked={topic.active} onClick={() => toggle(topic)}><span /></button></article>)}</div></section>{error && <p className="form-error" role="alert"><AlertTriangle size={16} />{error}</p>}<div className="admin-footer"><Button type="button" variant="ghost-danger" onClick={reset}><RotateCcw size={16} /> รีเซ็ตข้อมูล Demo</Button><div><Button type="button" variant="secondary" onClick={onClose}>ยกเลิก</Button><Button type="submit">บันทึกการตั้งค่า</Button></div></div></form></Dialog>;
}

function StatusBadge({ status }) { const meta = STATUS_META[status] || STATUS_META.pending; return <Badge status={meta.tone}>{status === "overdue" ? <AlertTriangle size={12} /> : status === "complete" ? <CheckCircle2 size={12} /> : <span className="badge-dot" />}{meta.label}</Badge>; }
function EmptyState({ icon: Icon, title, description, action, compact = false }) { return <div className={cn("empty-state", compact && "compact")}><span><Icon size={compact ? 21 : 28} /></span><strong>{title}</strong><p>{description}</p>{action}</div>; }
function formatBytes(size) { if (!Number.isFinite(size)) return "0 KB"; return size >= 1024 * 1024 ? `${(size / 1024 / 1024).toFixed(1)} MB` : `${Math.max(1, Math.round(size / 1024))} KB`; }
